# Generated by Django 3.2.5 on 2022-05-10 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UffFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_path', models.CharField(max_length=200)),
                ('file_name', models.CharField(max_length=200)),
                ('upload_time', models.TimeField()),
            ],
        ),
    ]
